# Generated by Django 4.1.7 on 2023-03-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_user', '0004_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='person_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
